[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

[font]
size = 14

[font.normal]
family = "Maple Mono"
style = "Medium"

[font.italic]
family = "Maple Mono"
style = "SemiBold Italic"

[font.bold]
family = "Maple Mono"
style = "Bold"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "CopySelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9
dynamic_padding = true
padding = { x = 6 }

# Unmap
[[keyboard.bindings]]
key = "="
mods = "Control"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "ReceiveChar"

[[keyboard.bindings]]
key = "0"
mods = "Control"
action = "ReceiveChar"

# Actual bindings
[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "_"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Backspace"
mods = "Control|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "["
mods = "Control"
action = "ToggleViMode"
